### PR TITLE
Adding code coverage and reporting

### PR DESCRIPTION
**Pull request by SteveGilham**
As per the wishlist item in [your blog post](https://tooslowexception.com/github-actions-and-sample-nuget-based-library/) for "more automated tests, like code coverage"

### CODE REVIEW

**Review by kkokosa — APPROVED** [review]
Great, thx! I wonder, if `altcover` (directly or indirectly) supports "badge" generations via https://shields.io/category/coverage?

**Comment by SteveGilham** [comment]
Two ways of doing this 

1. The `reportgenerator` tool will create badges locally, with the "-reporttypes:Badges" option; the file(s) would then need to be published locally
2. Use a third party site e.g. https://coveralls.io that publishes a badge; in this case [`coveralls.net`](https://www.nuget.org/packages/coveralls.net) will upload to an account on that site.

**Comment by kkokosa** [comment]
@SteveGilham do you have option 2 documented on `altcover` site? I wasn't able to find any.

**Comment by SteveGilham** [comment]
Only implicitly (as in it's in the build script for the CI server to run); the appropriate place for the documentation for a report uploader is at that tool's project site.  For coveralls.net, the readme is [here](https://github.com/csMACnz/coveralls.net/blob/master/README.md); that has a set of associated sample apps with various tooling combinations.

**Pull request merged**
